[workspace]
resolver = "3"
members = ["rustminify", "rustminify-cli"]

[workspace.package]
version = "0.3.0"
edition = "2024"

[workspace.dependencies]
anyhow = "1"
syn = { version = "2", features = ["full", "visit-mut"] }
